name: Backend CI

on:
  workflow_call:
    inputs:
      force-push:
        description: "Publish Docker image regardless of branch"
        type: boolean
        default: false

defaults:
  run:
    working-directory: ./backend

jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 17
          cache: maven
          cache-dependency-path: ./backend

      - name: Build with Maven
        run: mvn -B --no-transfer-progress package

      - name: Rename Jar
        shell: bash
        run: |
          mv target/*.jar target/emote-tracker-backend.jar

      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: emote-tracker-backend
          path: backend/target/emote-tracker-backend.jar

  docker:
    needs: maven
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download Jar
        uses: actions/download-artifact@v4
        with:
          name: emote-tracker-backend
          path: backend/build/

      - name: Extract Project version
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Add snapshot
        if: ${{ github.ref != 'refs/heads/master' }}
        run: |
          echo ${{ env.RELEASE_VERSION }}
          echo "RELEASE_VERSION=${{ env.RELEASE_VERSION }}-SNAPSHOT" >> $GITHUB_ENV

      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: tag365/emote-tracker-backend
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ env.RELEASE_VERSION }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          file: ./backend/build/Dockerfile
          push: ${{ inputs.force-push }}
          platforms: linux/amd64, linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}


