name: Backend CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  maven:
    defaults:
        run:
          working-directory: ./backend
    name: Maven
    runs-on: ubuntu-latest

    Maven-build:
      uses: ./.github/workflows/mvn_build.yaml
      secrets: inherit

    docker-build:
      needs: maven-build
      uses: ./.github/workflows/docker_build.yaml
      with:
        push: ${{ github.event.inputs.publish_artifacts == 'true' }}
      secrets: inherit

  checkstyle:
    defaults:
      run:
        working-directory: ./backend
    name: Checkstyle
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: mvn checkstyle:check --no-transfer-progress
