name: Backend CI

on:
  workflow_dispatch:
    inputs:
      publish_artifacts:
        description: "Publish Docker image regardless of branch"
        type: boolean
        default: false
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    working-directory: ./backend

jobs:
  maven-build:
    uses: ./.github/workflows/mvn_build.yaml
    secrets: inherit

  docker-build:
    needs: maven-build
    uses: ./.github/workflows/docker_build.yaml
    with:
      push: ${{ github.event.inputs.publish_artifacts == 'true' }}
    secrets: inherit

  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: mvn checkstyle:check --no-transfer-progress

  jacoco-report:
    if: ${{ github.event_name  == 'pull_request' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B --no-transfer-progress test

      - name: Jacoco report
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ./backend/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          update-comment: true
