name: Backend CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    working-directory: ./backend

jobs:
  maven-build:
    defaults:
      run:
        working-directory: ./backend
    uses: ./.github/workflows/mvn_build.yaml
    secrets: inherit

  docker-build:
    defaults:
      run:
        working-directory: ./backend
    needs: maven-build
    uses: ./.github/workflows/docker_build.yaml
    with:
      push: ${{ github.event.inputs.publish_artifacts == 'true' }}
    secrets: inherit

  checkstyle:
    defaults:
      run:
        working-directory: ./backend
    name: Checkstyle
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: mvn checkstyle:check --no-transfer-progress
