name: Backend CI

on:
  workflow_dispatch:
    inputs:
      publish_artifacts:
        description: "Publish Docker image regardless of branch"
        type: boolean
        default: false
  merge_group:
  push:
    branches:
    - master
  pull_request:
    path:
      - backend
      - api

defaults:
  run:
    working-directory: ./backend

jobs:
  maven-build:
    uses: ./.github/workflows/mvn_build.yaml
    secrets: inherit

  docker-build:
    needs: maven-build
    uses: ./.github/workflows/docker_build.yaml
    with:
      push: ${{ github.event.inputs.publish_artifacts == 'true' }}
    secrets: inherit

  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: mvn checkstyle:check --no-transfer-progress
