name: Backend CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  maven:
    defaults:
        run:
          working-directory: ./backend
    name: Maven
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Package
      run: mvn package --no-transfer-progress

  checkstyle:
    defaults:
      run:
        working-directory: ./backend
    name: Checkstyle
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: mvn checkstyle:check --no-transfer-progress
