name: CI

on:
  - push

jobs:
  maven:
    name: Maven
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Package
      run: mvn package --file \backend\pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: mvn checkstyle:check --file \backend\pom.xml
