name: CI

on:
  - push

jobs:
  maven:
    name: Maven
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Package
      run: mvn package --file backend/pom.xml

  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: mvn checkstyle:check --file backend/pom.xml
