name: Docker

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean
        default: false

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download Jar
        uses: actions/download-artifact@v4
        with:
          name: emote-tracker-backend
          path: backend/build/

      - name: Extract Project version
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Add snapshot
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          echo ${{ env.RELEASE_VERSION }}
          echo "RELEASE_VERSION=${{ env.RELEASE_VERSION }}-SNAPSHOT" >> $GITHUB_ENV

      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: tag365/emote-tracker-backend
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ env.RELEASE_VERSION }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: ./backend/build
          push: ${{ inputs.push }}
          platforms: linux/amd64, linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
