name: Docker

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download Jar
        uses: actions/download-artifact@v3
        with:
          name: command-api
          path: build/

      - name: Extract Project version
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Add snapshot
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          echo ${{ env.RELEASE_VERSION }}
          echo "RELEASE_VERSION=${{ env.RELEASE_VERSION }}-SNAPSHOT" >> $GITHUB_ENV
    
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./build
          push: ${{ inputs.push }}
          tags: tag365/tm-streams-support-api:${{ env.RELEASE_VERSION }} , tag365/tm-streams-support-api:latest
