name: Frontend CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    path:
      - backend
      - api
jobs:
  node:
    defaults:
      run:
        working-directory: ./frontend
    name: Node
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm
          cache-dependency-path: ./frontend

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8.6.*

      - name: Install dependencies
        run: pnpm install

      - name: Generate api code
        run: pnpm "generate api"
