name: Frontend CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - 'frontend/**'
      - 'api/**'
      - '.github/**'

  workflow_dispatch:
    inputs:
      force-push:
        description: Push artifact regardless of branch
        type: boolean
        default: false

jobs:
  node:
    defaults:
      run:
        working-directory: ./frontend
    name: Node
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm
          cache-dependency-path: ./frontend

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8.6.*

      - name: Install dependencies
        run: pnpm install

      - name: Generate api code
        run: pnpm "generate api"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Project version
        run: |
          echo "RELEASE_VERSION=$(npm pkg get version | tr -d \")" >> $GITHUB_ENV

      - name: Add snapshot
        if: ${{ github.ref != 'refs/heads/master' }}
        run: |
          echo ${{ env.RELEASE_VERSION }}
          echo "RELEASE_VERSION=${{ env.RELEASE_VERSION }}-SNAPSHOT" >> $GITHUB_ENV

      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: tag365/emote-tracker
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ env.RELEASE_VERSION }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: ${{ github.ref == 'refs/heads/master' || inputs.force-push == true }}
          platforms: linux/amd64, linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
  staging:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm
          cache-dependency-path: ./frontend

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8.6.*

      - name: Install dependencies
        run: pnpm install

      - name: Generate api code
        run: pnpm "generate api"

      - name: Build staging
        run: pnpm staging

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: emote-tracker
          path: |
            ./frontend/build
            ./frontend/package.json
            ./frontend/pnpm-lock.yaml
