name: Frontend CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  node:
    defaults:
      run:
        working-directory: ./frontend
    name: Maven
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        working-directory: ./frontend
        with:
          node-version: '18.x'
          cache: npm

      - name: Install
        run: npm install
