name: Merge Queue
on:
  merge_group:

jobs:
  frontend:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm
          cache-dependency-path: ./frontend

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          version: 8.6.*

      - name: Install dependencies
        run: pnpm install

      - name: Generate api code
        run: pnpm "generate api"

      - name: Build staging
        run: pnpm staging

  backend:
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B --no-transfer-progress package
      - name: Rename Jar
        shell: bash
        run: |
          mv target/*.jar target/emote-tracker-backend.jar
