name: Maven

on:
  workflow_call:

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B --no-transfer-progress package
      - name: Rename Jar
        shell: bash
        run: | 
          mv target/*.jar target/emote-tracker-backend.jar
      - name: Upload Jar
        uses: actions/upload-artifact@v3
        with:
          name: emote-tracker-backend
          path: backend/target/emote-tracker-backend.jar
