name: Publish docker image
on:
  push:
    tags:
      - "*"

jobs:
  maven:
    uses: ./.github/workflows/mvn_build.yaml
  docker:
    needs: maven
    uses: ./.github/workflows/docker_build.yaml
    with:
      push: true
    secrets: inherit
