name: Static Analysis of a pull request
on:
  pull_request:

jobs:
  checkstyle:
    defaults:
      run:
        working-directory: ./backend
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mvn checkstyle:check --no-transfer-progress

  jacoco-report:
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B --no-transfer-progress test

      - name: Jacoco report
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ./backend/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          update-comment: true
